apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-tools
  template:
    metadata:
      labels:
        app: media-tools
    spec:
      containers:
      - name: media-tools
        image: lalalaciccio/media-tools:latest
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]