apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-utils
  template:
    metadata:
      labels:
        app: media-utils
    spec:
      containers:
      - name: media-utils
        image: lalalaciccio/media-tools:latest
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        hostPath:
          path: ./scripts
